name: Sync to S3

on: [push, pull_request]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ vars.ENGRID_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ENGRID_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ENGRID_S3_SECRET_KEY }}
          SOURCE_DIR: 'dist'
          DEST_DIR: '${{ github.event.repository.name }}/${{ github.head_ref || github.ref_name }}'
